server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_account_book?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: root
    password: T123456789

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.accountbookserver.entity
  configuration:
    map-underscore-to-camel-case: true
